extends RefCounted
const Controller = preload("res://presentation/game_controller.gd")
const Content = preload("res://presentation/content_store.gd")
var checks := 0
var failures := 0

func check(value: bool, message: String) -> void:
	checks += 1
	if not value:
		failures += 1
		push_error("FAIL: controller " + message)

func run() -> bool:
	print("TEST intent controller: draft privacy / rejection / detached results / lifecycle")
	var content := Content.new()
	check(content.reload(), "load content")
	var game := Controller.new(content)
	check(game.screen_state().screen == "MENU", "initial menu")
	check(not game.dispatch("DRAW_TILE").ok, "covered command is refused")
	game.select_tile("stale-widget")
	game.choose_ballot(true)
	game.submit_rating(3)
	check(game.current_view().is_empty() and game.selected_tiles().is_empty(), "late menu intentions do nothing")
	game.start_game(42)
	check(game.screen_state().screen == "HANDOFF" and game.current_view().is_empty(), "new session covered")
	game.accept_handoff()
	game.next_round()
	var dealer: String = game.current_view().round.dealer_id
	game.choose_seat(dealer)
	game.accept_handoff()
	var view := game.current_view()
	var card: String = view.round.hand[0].id
	var revision: int = view.revision
	view.round.hand.clear()
	check(game.current_view().round.hand.size() == 14, "projection snapshot cannot mutate cached view")
	game.select_tile(card)
	game.toggle_meme("meme.happy")
	var draft := game.draft()
	draft.tile_ids.clear()
	draft.meme_keys.append("fake")
	check(game.selected_tiles() == [card] and game.selected_memes() == ["meme.happy"], "draft getters are detached")
	check(game.current_view().revision == revision, "selection never advances authority")
	var failed := game.dispatch("DISCARD_TILE", {"tile_id": "foreign-tile"})
	check(not failed.ok, "invalid command fails")
	check(game.selected_tiles() == [card] and game.selected_memes() == ["meme.happy"], "failure keeps editable draft")
	failed.view.round.hand.clear()
	check(game.current_view().round.hand.size() == 14, "receipt view cannot overwrite controller view")
	game.choose_seat("invalid-seat")
	check(game.current_view().is_empty() and not game.screen_state().handoff_allowed, "invalid seat still covers previous player")
	check(game.draft().tile_ids.is_empty() and game.draft().meme_keys.is_empty(), "invalid handoff also clears draft")
	game.accept_handoff()
	check(game.current_view().is_empty(), "invalid handoff cannot reveal hand")
	game.choose_seat(dealer)
	game.accept_handoff()
	for tile in game.current_view().round.hand.slice(0, 2): game.select_tile(tile.id)
	game.toggle_meme("meme.happy")
	game.play_sentence()
	check(game.current_view().round.phase == "AWAIT_VOTES", "proposal submitted")
	check(game.draft().tile_ids.is_empty() and game.draft().meme_keys.is_empty(), "successful proposal clears draft")
	game.choose_ballot(true)
	check(game.draft().ballot_choice == null, "owner cannot create ballot draft")
	var voter: String = "东" if dealer != "东" else "南"
	game.choose_seat(voter)
	game.accept_handoff()
	revision = game.current_view().revision
	game.choose_ballot(false)
	check(game.draft().ballot_choice == false, "opposition enters rating step too")
	check(game.current_view().revision == revision, "decision not yet sent")
	game.submit_rating(99)
	check(game.draft().ballot_choice == false and not game.current_view().round.pending_sentence.has_voted, "rejected score keeps decision for retry")
	game.reset_ballot()
	check(game.draft().ballot_choice == null, "back clears only decision")
	game.choose_ballot(true)
	game.choose_seat(voter)
	check(game.draft().ballot_choice == null, "handoff cancels unsubmitted decision")
	game.accept_handoff()
	game.choose_ballot(false)
	game.submit_rating(1)
	check(game.current_view().round.pending_sentence.has_voted, "decision and rating submit together")
	game.choose_ballot(true)
	check(game.draft().ballot_choice == null, "submitted voter cannot start a second ballot")
	game.choose_seat("东")
	game.accept_handoff()
	var ended := game.dispatch("END_GAME")
	check(ended.ok and game.current_view().round.phase == "ABORTED", "host can cancel pending vote")
	check(game.draft().ballot_choice == null and game.selected_memes().is_empty(), "end clears all local ballot and meme data")
	game.show_menu()
	check(game.screen_state().screen == "MENU" and game.current_view().is_empty(), "menu drops last projection")
	check(not game.dispatch("DRAW_TILE").ok, "old session cannot accept menu command")
	game.start_game(42)
	game.accept_handoff()
	check(game.current_view().round == null and game.current_view().round_number == 0, "restart has fresh session")
	game.next_round()
	game.choose_seat(game.current_view().round.active_player_id)
	game.accept_handoff()
	game.select_tile(game.current_view().round.hand[0].id)
	game.toggle_meme("meme.happy")
	game.show_menu()
	check(game.selected_tiles().is_empty() and game.selected_memes().is_empty(), "return to menu also clears unsent draft")
	check(not game.draft().meme_expanded and game.draft().drawn_tile.is_empty(), "menu clears presentation flags")
	return true
