"""Build an uploadable WeChat Game: small main package, lazy animation subpackages.

Run build-preview-content.py --animations-only first to regenerate high-quality GIF
atlases. This builder never recompresses JPEGs and never publishes/uploads anything.
"""
from __future__ import annotations
import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'apps' / 'wechat-preview'
TARGET = ROOT / 'apps' / 'wechat-phone-preview'
MAIN_LIMIT = 3_800_000  # Conservative headroom below 4 MB.
PACK_LIMIT = 3_500_000
TOTAL_LIMIT = 19_000_000  # Conservative project budget, not a claim about account quota.


def manifest(path):
    source = path.read_text(encoding='utf-8')
    match = re.search(r'var CONTENT = (\{.*\});', source)
    if not match:
        raise RuntimeError(f'No content manifest in {path}')
    return source, match, json.loads(match.group(1))


def generated_paths(content, config):
    paths = {m['path'] for m in content['memes']}
    paths.update(m['animation']['path'] for m in content['memes'] if m.get('animation'))
    paths.update(content['ui_paths'].values())
    paths.update(p['root'].rstrip('/') + '/game.js' for p in config.get('subpackages', []))
    return paths


def target_path(relative):
    target = (TARGET / relative).resolve()
    if not target.is_relative_to(TARGET.resolve()):
        raise RuntimeError('Output path escapes generated package')
    return target


def copy(relative, destination=None):
    output = target_path(destination or relative)
    output.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(SOURCE / relative, output)


def main():
    source, match, content = manifest(SOURCE / 'content.js')
    previous_paths = set()
    if (TARGET / 'content.js').exists():
        _, _, previous = manifest(TARGET / 'content.js')
        previous_config = json.loads((TARGET / 'game.json').read_text(encoding='utf-8'))
        previous_paths = generated_paths(previous, previous_config)
    TARGET.mkdir(parents=True, exist_ok=True)
    for relative in ('game.js', 'core.bundle.js', 'network-client.js', 'lan-client.js',
                     'gif-codec.js', 'custom-memes.js', 'lan-assets.js'):
        copy(relative)
    for meme in content['memes']:
        copy(meme['path'])
    for relative in content['ui_paths'].values():
        copy(relative)

    packs = []
    for meme in content['memes']:
        animation = meme.get('animation')
        if not animation:
            continue
        size = (SOURCE / animation['path']).stat().st_size
        if size + 100 > PACK_LIMIT:
            raise RuntimeError(f"Animation exceeds package budget: {animation['path']}")
        if not packs or packs[-1]['bytes'] + size > PACK_LIMIT:
            name = f'animations-{len(packs) + 1:02d}'
            packs.append({'name': name, 'root': f'packs/{name}/', 'bytes': 60})
            entry = target_path(packs[-1]['root'] + 'game.js')
            entry.parent.mkdir(parents=True, exist_ok=True)
            entry.write_text('// Animation assets only; loaded on demand.\n', encoding='utf-8')
        pack = packs[-1]
        destination = pack['root'] + Path(animation['path']).name
        copy(animation['path'], destination)
        animation.update(path=destination, package=pack['name'])
        pack['bytes'] += size

    game_config = json.loads((SOURCE / 'game.json').read_text(encoding='utf-8'))
    game_config['subpackages'] = [{k: p[k] for k in ('name', 'root')} for p in packs]
    (TARGET / 'game.json').write_text(json.dumps(game_config, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    content['build_profile'] = 'clear-animations-subpackages'
    payload = json.dumps(content, ensure_ascii=False, separators=(',', ':'))
    generated = source[:match.start(1)] + payload + source[match.end(1):]
    generated = generated.replace('Generated by scripts/build-preview-content.py', 'Generated by scripts/build-wechat-phone-preview.py', 1)
    (TARGET / 'content.js').write_text(generated, encoding='utf-8')
    project = json.loads((SOURCE / 'project.config.json').read_text(encoding='utf-8'))
    project['projectname'] = 'word-tiles-wechat-phone-preview'
    private_config = ROOT / 'project.private.config.json'
    project['libVersion'] = (json.loads(private_config.read_text(encoding='utf-8'))['libVersion']
                             if private_config.exists() else '3.17.3')
    project.setdefault('setting', {})['minified'] = True
    project['packOptions'] = {'ignore': [{'type': 'file', 'value': 'README.md'}], 'include': []}
    (TARGET / 'project.config.json').write_text(json.dumps(project, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

    # Prune only assets listed by the previous generated manifest, never arbitrary files.
    current_paths = generated_paths(content, game_config)
    for relative in sorted(previous_paths - current_paths):
        obsolete = target_path(relative)
        if obsolete.is_file():
            obsolete.unlink()
    files = [f for f in TARGET.rglob('*') if f.is_file()]
    total = sum(f.stat().st_size for f in files)
    subpackage_sizes = {p['name']: sum(f.stat().st_size for f in target_path(p['root']).rglob('*') if f.is_file()) for p in packs}
    main_bytes = total - sum(subpackage_sizes.values())
    if main_bytes >= MAIN_LIMIT or total >= TOTAL_LIMIT or any(n >= PACK_LIMIT for n in subpackage_sizes.values()):
        raise RuntimeError(f'Package budget exceeded: main={main_bytes}, total={total}, subpackages={subpackage_sizes}')
    report = {'main_bytes': main_bytes, 'total_bytes': total, 'main_budget': MAIN_LIMIT,
              'total_budget': TOTAL_LIMIT, 'subpackage_bytes': subpackage_sizes,
              'animation_count': sum('animation' in m for m in content['memes']),
              'max_frame_edge': max(max(m['animation']['frame_width'], m['animation']['frame_height']) for m in content['memes'] if 'animation' in m),
              'max_atlas_decoded_bytes': max(m['animation'].get('decoded_bytes', 0) for m in content['memes'] if 'animation' in m),
              'code_minification': 'WeChat developer tools setting.minified=true; sizes above are unminified disk bytes'}
    (ROOT / 'docs/PERFORMANCE_BUILD.json').write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
